### PR TITLE
feat: adds s tag as allowed

### PR DESCRIPTION
**Pull request by taleksei**
https://jira.railsc.ru/browse/GOODS-1146

:link: https://github.com/abak-press/apress-text_editor/pull/72

### CODE REVIEW

**Comment by taleksei** [comment]
@cynek сделаем отдельную ветку?

**Comment by cynek** [comment]
https://github.com/abak-press/string_tools/tree/tags_availability с master'а

**Comment by taleksei** [comment]
@cynek @spyderdfx

**Comment by taleksei** [comment]
merge

**Pull request merged**
